- name: get makemkvcon stat
  stat:
    path: /usr/bin/makemkvcon
  register: st
- import_tasks: makemkv-bin.yml
  when: not st.stat.exists
- name: get makemkv stat     
  stat:
    path: /usr/bin/makemkv    
  register: st
- import_tasks: makemkv-oss.yml
  when: not st.stat.exists

