- name: download makemkv bin
  unarchive:
    src: http://www.makemkv.com/download/makemkv-bin-{{ makemkv_version }}.tar.gz
    dest: /home/whs/Downloads
    remote_src: yes
- name: create makemkv bin tmp directory
  file:
    path: /home/whs/Downloads/makemkv-bin-{{ makemkv_version }}/tmp
    state: directory
- name: accept makemkv bin eula
  template:
    src: eula_accepted
    dest: /home/whs/Downloads/makemkv-bin-{{ makemkv_version }}/tmp/eula_accepted
- name: install makemkv bin
  make:
    chdir: /home/whs/Downloads/makemkv-bin-{{ makemkv_version }}
    target: install
  become: yes
