- name: install nvim
  hosts: all
  roles:
  - common
  - htpc
  - nvim
  - janus
  - borg
  - keepass
  - kubectl
  - minikube
  - helm
  - mediawiki
  - chromium
  - node
  - yarn
  - gatsby
  - youtube-dl
  - builder
  - filezilla
  - sbt
  - awscli
  - brasero
