- name: get vagrant latest rpm
  shell: curl -s https://www.vagrantup.com/downloads.html | grep x86_64.rpm | cut -d '"' -f 8
  register: vagrant_rpm_result
- name: download vagrant
  get_url:
    url: "{{ vagrant_rpm_result.stdout }}"
    dest: "{{ ansible_env.HOME }}/Downloads/{{ vagrant_rpm_result.stdout | basename }}"
- name: install vagrant
  dnf:
    name: "{{ ansible_env.HOME }}/Downloads/{{ vagrant_rpm_result.stdout | basename }}"
    state: present
  become: yes
