- name: install zsh
  dnf:
    name: zsh
    state: present
  become: yes
- name: change shell to zsh
  user:
    name: "{{ ansible_env.USERNAME }}"
    shell: /usr/bin/zsh
  become: yes
- name: install zplug
  shell: curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
  args:
    creates: "{{ ansible_env.HOME }}/.zplug"
