- name: download cuda rpm
  get_url:
    url: https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda-repo-fedora29-10-1-local-10.1.105-418.39-1.0-1.x86_64.rpm
    dest: "{{ ansible_env.HOME }}/Downloads/cuda-repo-fedora29-10-1-local-10.1.168-418.67-1.0-1.x86_64.rpm"
- name: install the cuda rpm
  dnf:
    name: "xorg-x11-drv-nvidia-cuda,{{ ansible_env.HOME }}/Downloads/cuda-repo-fedora29-10-1-local-10.1.168-418.67-1.0-1.x86_64.rpm"
    state: present
  become: yes
- name: add cuda repo excludes
  lineinfile:
    path: /etc/yum.repos.d/cuda-10-1-local-10.1.168-418.67.repo
    line: exclude=akmod-nvidia*,kmod-nvidia*,*nvidia*,nvidia-*,cuda-nvidia-kmod-common,dkms-nvidia,nvidia-libXNVCtrl
  become: yes
