- name: install yarn repo
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
  become: yes
- name: install yarn
  dnf:
    name: yarn
    state: present
  become: yes
