- name: install php mbstring, xml and json
  dnf:
    name: php-mbstring,php-xml,php-json
    state: present
  become: yes
- name: get mediawiki latest version url
  shell: curl -s https://www.mediawiki.org/wiki/Download | grep "Download MediaWiki" | cut -d '"' -f 28
  register: mediawiki_url
- name: get mediawiki folder name
  shell: "basename -s .tar.gz {{ mediawiki_url.stdout }}"
  register: mediawiki_folder
- name: install mediawiki
  unarchive:
    src: "{{ mediawiki_url.stdout }}"
    dest: /var/www/html
    remote_src: yes
    creates: "/var/www/html/{{ mediawiki_folder.stdout }}"
  become: yes
