- name: install nvim
  dnf:
    name: neovim
    state: present
  become: yes
- name: create nvim autoload directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
    state: directory
- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
- name: install ack
  dnf:
    name: ack
    state: present
  become: yes
- name: install janus
  shell: curl -L https://bit.ly/janus-bootstrap | bash
  args:
    creates: "{{ ansible_env.HOME }}/.vim/janus"
    executable: /bin/bash
- name: link dotvim
  file:
    src: "{{ ansible_env.HOME }}/.vim"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
- name: link vimrc
  file:
    src: "{{ ansible_env.HOME }}/.vimrc"
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
    state: link
